markdown: kramdown
baseurl: /photos
exclude: ['auth', 'README.md']

defaults:
  - scope:
      path: ""
    values:
      layout: ""
  - scope:
      path: "data"
    values:
      layout: "data"
  - scope:
      path: "albums"
    values:
      layout: "album"
