markdown: kramdown
photo_baseurl: http://s3.bertspaan.nl/
exclude: ['auth', 'README.md']

defaults:
  - scope:
      path: ""
    values:
      layout: ""
  - scope:
      path: "data"
    values:
      layout: "data"
  - scope:
      path: "albums"
    values:
      layout: "album"
